### PR TITLE
Added support for generating di files in a directory to the gdc and dmd builder

### PR DESCRIPTION
**Pull request by Alexibu**
Hi Russel,
I have managed to get the gdc builder to do the correct things with .di files. 
Please have a look.
I have a minimal test project to base a scons repository test script on, and would be happy to convert the other compilers and add the test to the scons repo to with your guidance.
Alex

### CODE REVIEW

**Comment by russel** [comment]
@Alexibu I am not ignoring the building changeset, I just cannot pull it into master just yet – easier to avoid an awkwardness locally. I think I will try and create a feature branch in which we can put this into the mainline repository. Then when the "blocker" is fixed we can look at merging this into master.

**Comment by russel** [comment]
I have pulled these changes into a new branch di-processing, so I am closing this pull request apparently un-merged. The problem for the moment is that there are no tests, so these changes cannot be proposed for incorporation into SCons: the rule is no tests, no documentation, no merging. Once there are tests and some documentation, I can merge into master and create a pull request for merging into the mainline.

**Comment by Alexibu** [comment]
There is no place for tests in this repository. Should I make a pull request with tests to your SCons on bitbucket ?
Also, this code finds a bug in the way Scons handles builders with multiple output files. It causes everything to be built every time. I think is beyond my capabilities to fix. I can make a failing test for it. What do you think I should do with it ?

**Comment by russel** [comment]
@Alexibu I have set up locally to allow staging into the mainline repository and just realised I hadn't put a marker test into the repository. If you put an end-to-end test into a directory test/new_test/<name-of-test-directory> – that is what I did but didn't commit. Failing that email me the end-to-end test files and I will do it here.

**Pull request closed without merging**
